FROM ubuntu:22.04

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update

RUN apt-get install -y wget curl build-essential cmake locales sudo tzdata

RUN wget --progress=dot:giga --no-check-certificate https://developer.arm.com/-/media/Files/downloads/gnu/13.2.rel1/binrel/arm-gnu-toolchain-13.2.rel1-x86_64-arm-none-eabi.tar.xz -O /opt/gcc-arm-none-eabi.tar.xz
RUN mkdir /opt/gcc-arm-none-eabi
RUN tar xf /opt/gcc-arm-none-eabi.tar.xz -C /opt/gcc-arm-none-eabi --strip-components 1
RUN rm /opt/gcc-arm-none-eabi.tar.xz
ENV PATH=$PATH:/opt/gcc-arm-none-eabi/bin

RUN ln -fs /usr/share/zoneinfo/Europe/Paris /etc/localtime
RUN sudo dpkg-reconfigure -f noninteractive tzdata

RUN mkdir -p /workspaces/project
WORKDIR /workspaces/project

# For debugger
RUN apt update
RUN apt-get install -y git zlib1g-dev libffi-dev liblzma-dev libncursesw5-dev libreadline-dev libsqlite3-dev libbz2-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev
RUN curl https://pyenv.run | bash
ENV PYENV_ROOT="/root/.pyenv"
ENV PATH="$PYENV_ROOT/bin:$PATH"
RUN pyenv install 3.8.18
RUN mkdir -p /usr/local/bld-tools
RUN ln -s $PYENV_ROOT/versions/3.8.18 /usr/local/bld-tools/bld-tools-virtual-env
RUN ln -s /usr/lib/x86_64-linux-gnu/libncursesw.so.6 /usr/lib/x86_64-linux-gnu/libncursesw.so.5
RUN ln -s /usr/lib/x86_64-linux-gnu/libtinfo.so.6 /usr/lib/x86_64-linux-gnu/libtinfo.so.5

# For dev compilation
RUN apt-get install -y git zsh
RUN chsh -s /bin/zsh root
RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
RUN git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
RUN git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
RUN sed -i 's/ZSH_THEME="robbyrussell"/ZSH_THEME="tjkirch"/g' ~/.zshrc
RUN sed -i 's/plugins=(git)/plugins=(git zsh-autosuggestions zsh-syntax-highlighting)/g' ~/.zshrc
RUN git config --global --add oh-my-zsh.hide-status 1
RUN git config --global --add oh-my-zsh.hide-dirty 1
